# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-11-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181126_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=20, verbose_name='작성자'),
        ),
    ]
